'use client';
import { ChangeEvent, useMemo, useState } from 'react';
import formSample from '@/data/samples/form16.sample.json';
import aisSample from '@/data/samples/ais.sample.json';
import formTemplate from '@/data/templates/form16.template.json';
import aisTemplate from '@/data/templates/ais.template.json';
import { inr } from '@/lib/format/inr';
import { emptyInput } from '@/lib/tax/compute';
import { reconcile } from '@/lib/reconcile/reconcile';
import type { Ais, Form16 } from '@/lib/reconcile/types';
import { aisSchema, form16Schema } from '@/lib/validation/schemas';

function download(name: string, data: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
type Kind = 'form' | 'ais';
export default function ReconcilePage() {
  const [form, setForm] = useState<Form16 | null>(null); const [ais, setAis] = useState<Ais | null>(null); const [formText, setFormText] = useState(''); const [aisText, setAisText] = useState(''); const [message, setMessage] = useState(''); const [details, setDetails] = useState(false);
  const result = useMemo(() => form && ais ? reconcile({ form16: form, ais, declared: { ...emptyInput, salary: { ...emptyInput.salary, gross: form.salary.gross, basic: form.salary.basic, da: form.salary.da, hraReceived: form.salary.hraReceived, otherExemptAllowances: form.salary.exemptAllowances, employerNpsContribution: form.salary.employerNpsContribution }, deductions: { ...emptyInput.deductions, section80C: form.deductionsConsidered['80C'] ?? 0, section80Dself: form.deductionsConsidered['80D'] ?? 0, section80CCD1B: form.deductionsConsidered['80CCD1B'] ?? 0 }, tdsPaid: form.totalTds } }) : null, [form, ais]);
  function load(kind: Kind, data: unknown) { const checked = kind === 'form' ? form16Schema.safeParse(data) : aisSchema.safeParse(data); if (!checked.success) { setMessage(checked.error.issues.map((issue) => issue.message).join('; ')); return; } if (kind === 'form') setForm(checked.data as Form16); else setAis(checked.data as Ais); setMessage(`${kind === 'form' ? 'Form 16' : 'AIS'} loaded.`); }
  function paste(kind: Kind) { try { load(kind, JSON.parse(kind === 'form' ? formText : aisText)); } catch (error) { setMessage(`JSON could not be parsed: ${error instanceof Error ? error.message : 'unknown error'}`); } }
  function upload(kind: Kind, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2097152) { setMessage('File is larger than 2MB. Choose a smaller JSON file.'); return; } if (file.type && file.type !== 'application/json') { setMessage('Choose a JSON file; the previous document is unchanged.'); return; } const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); if (parsed.documentType === (kind === 'form' ? 'AIS' : 'FORM16')) { setMessage('That document belongs in the other panel. Use Swap documents to move it.'); kind === 'form' ? setAis(parsed) : setForm(parsed); } else load(kind, parsed); } catch (error) { setMessage(`JSON could not be parsed: ${error instanceof Error ? error.message : 'unknown error'}`); } }; reader.readAsText(file); }
  async function copyChecklist() { if (!result) return; const markdown = result.flags.map((flag) => `- [ ] ${flag.title}: ${flag.suggestedAction}`).join('\n'); await navigator.clipboard.writeText(markdown); setMessage('Checklist copied to the clipboard.'); }
  return <><p className="eyebrow">Engine 3</p><h1>Check Form 16 and AIS</h1><p className="muted">Form 16 is your employer’s salary and TDS record. AIS is the tax department’s record of income reports from banks, employers and other sources.</p><div className="two">{([{ kind: 'form' as const, title: 'Form 16', sample: formSample, template: formTemplate, text: formText, setText: setFormText }, { kind: 'ais' as const, title: 'AIS', sample: aisSample, template: aisTemplate, text: aisText, setText: setAisText }]).map((panel) => <section className="card stack" key={panel.kind}><h2>{panel.title}</h2><div className="actions"><button className="button" onClick={() => load(panel.kind, panel.sample)}>Load sample</button><button className="button secondary" onClick={() => download(`${panel.kind}.template.json`, panel.template)}>Download blank template</button><label className="button secondary">Upload JSON<input hidden type="file" accept="application/json,.json" onChange={(event) => upload(panel.kind, event)} /></label></div><label>Paste structured JSON<textarea value={panel.text} onChange={(event) => panel.setText(event.target.value)} placeholder={`Paste ${panel.title} JSON here`} /></label><button className="button secondary" onClick={() => paste(panel.kind)}>Use pasted JSON</button></section>)}</div><div className="actions" style={{ marginTop: 12 }}>{message && <span role="status">{message}</span>}</div>{result && <section><h2>Notice risk score</h2><div className="summary"><strong className="figure">{result.risk.score}/100 — {result.risk.band}</strong><button className="button secondary" onClick={() => setDetails(!details)} aria-expanded={details}>Show score working</button>{details && <ul>{result.risk.contributions.map((item) => <li key={item.label}>{item.label}: {item.points} points</li>)}</ul>}</div><div className="actions" style={{ marginTop: 12 }}><button className="button" onClick={copyChecklist}>Copy all flags as a checklist</button></div><p className="muted">Undeclared AIS income excluding probable duplicates: {inr(result.undeclaredIncomeTotal)}</p>{(['BLOCKER', 'WARNING', 'INFO'] as const).map((severity) => { const flags = result.flags.filter((flag) => flag.severity === severity); return flags.length ? <section key={severity}><h2>{severity}s ({flags.length})</h2>{flags.map((flag) => <article className={`card flag-${severity}`} key={flag.id}><div className="actions"><span className="pill">{flag.severity}</span><strong>{flag.title}</strong><span className="muted">Confidence: {flag.confidence}</span></div><p>{flag.whatItMeans}</p><p><strong>If ignored:</strong> {flag.ifIgnored}</p><p><strong>Next:</strong> {flag.suggestedAction}</p><p className="figure">Form 16 {inr(flag.evidence.formSixteenValue)} · AIS {inr(flag.evidence.aisValue)} · Difference {inr(flag.evidence.difference)} {flag.evidence.aisEntryIds?.length ? `· AIS ${flag.evidence.aisEntryIds.join(', ')}` : ''}</p></article>)}</section> : null; })}</section>}</>;
}
