'use client';
import { useState } from 'react';
import { inr } from '@/lib/format/inr';
import type { Comparison } from '@/lib/tax/types';

export function ComparisonLedger({ comparison }: { comparison: Comparison }) {
  const [open, setOpen] = useState<number | null>(null); const winnerColumn = comparison.winner === 'tie' ? null : comparison.winner;
  return <section aria-labelledby="ledger-title"><h2 id="ledger-title">Regime comparison</h2><p className="muted">Select a row to see its working. Every value is computed locally from the figures entered.</p><table className="ledger"><thead><tr><th>Working</th><th className={winnerColumn === 'old' ? 'winner' : ''}>Old regime {winnerColumn === 'old' && <small> — LOWER BY {inr(comparison.difference)}</small>}</th><th className={winnerColumn === 'new' ? 'winner' : ''}>New regime {winnerColumn === 'new' && <small> — LOWER BY {inr(comparison.difference)}</small>}</th></tr></thead><tbody>{comparison.old.steps.map((oldStep, index) => { const newStep = comparison.new.steps[index]; const expanded = open === index; return <tr key={oldStep.number}><td data-label="Working"><button className="row-button" onClick={() => setOpen(expanded ? null : index)} aria-expanded={expanded}><strong>{oldStep.number}. {oldStep.label}</strong> {oldStep.section && <span className="eyebrow">{oldStep.section}</span>}</button>{expanded && <div className="working">Old: {oldStep.working}<br />New: {newStep.working}</div>}</td><td data-label="Old regime" className={`number ${winnerColumn === 'old' ? 'winner' : ''}`}>{inr(oldStep.value)}</td><td data-label="New regime" className={`number ${winnerColumn === 'new' ? 'winner' : ''}`}>{newStep.disallowed && oldStep.value !== 0 ? <><span className="strike">{inr(oldStep.value)}</span><small className="muted"> not allowed in new regime</small></> : inr(newStep.value)}</td></tr>; })}</tbody></table>{comparison.winner === 'tie' && <p className="notice">Both regimes compute the same. The new regime is the default and needs no paperwork.</p>}<div className="sticky"><span className="figure">Old {inr(comparison.old.totalTax)}</span> · <span className="figure">New {inr(comparison.new.totalTax)}</span> · {comparison.winner === 'tie' ? 'Same computed tax' : `${comparison.winner === 'old' ? 'Old' : 'New'} computes lower by ${inr(comparison.difference)}`}</div></section>;
}
